version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./logs:/app/logs
    ports:
      - 8003:8000
    env_file:
      - .env
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db   # Use service name
      POSTGRES_DB: social_network  # Your database name
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@123

  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
     POSTGRES_DB: social_network
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: admin@123d

volumes:
  postgres_data:








